<?php

use Illuminate\Database\Seeder;
use App\Model\CardList;

class CardListsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CardList::create([
            'id'=>1,
            'color_id'=>1,
            'pack_id'=>'B01',
            'name'=>'ライラプス',
            'cost'=>'2',
            'power'=>'2500',
        ]);
        CardList::create([
            'id'=>2,
            'color_id'=>1,
            'pack_id'=>'B01',
            'name'=>'刀職人 二刀',
            'cost'=>'2',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>3,
            'color_id'=>1,
            'pack_id'=>'B01',
            'name'=>'コールアルマジロ',
            'cost'=>'2',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>4,
            'color_id'=>1,
            'pack_id'=>'B01',
            'name'=>'ゴールドピーコク',
            'cost'=>'3',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>5,
            'color_id'=>1,
            'pack_id'=>'B01',
            'name'=>'クレオパトラ',
            'cost'=>'3',
            'power'=>'4500',
        ]);
        CardList::create([
            'id'=>6,
            'color_id'=>2,
            'pack_id'=>'B01',
            'name'=>'アスタチン',
            'cost'=>'2',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>7,
            'color_id'=>2,
            'pack_id'=>'B01',
            'name'=>'抹消イレイス',
            'cost'=>'2',
            'power'=>'3000',
        ]);
        CardList::create([
            'id'=>8,
            'color_id'=>1,
            'pack_id'=>'B02',
            'name'=>'森蘭丸',
            'cost'=>'2',
            'power'=>'2000',
        ]);
        CardList::create([
            'id'=>9,
            'color_id'=>1,
            'pack_id'=>'B02',
            'name'=>'シルバーフォックス',
            'cost'=>'2',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>10,
            'color_id'=>1,
            'pack_id'=>'B02',
            'name'=>'魔狼フェンリル',
            'cost'=>'2',
            'power'=>'3000',
        ]);
        CardList::create([
            'id'=>11,
            'color_id'=>1,
            'pack_id'=>'B02',
            'name'=>'アフロディーテ',
            'cost'=>'3',
            'power'=>'5000',
        ]);
        CardList::create([
            'id'=>12,
            'color_id'=>1,
            'pack_id'=>'B02',
            'name'=>'クイックドロー',
            'cost'=>'3',
            'power'=>'4500',
        ]);
        CardList::create([
            'id'=>13,
            'color_id'=>1,
            'pack_id'=>'B03',
            'name'=>'傾城の美女',
            'cost'=>'2',
            'power'=>'3500',
        ]);
        CardList::create([
            'id'=>14,
            'color_id'=>1,
            'pack_id'=>'B03',
            'name'=>'クォーツクラブ',
            'cost'=>'3',
            'power'=>'5000',
        ]);
        CardList::create([
            'id'=>15,
            'color_id'=>1,
            'pack_id'=>'B03',
            'name'=>'エレファント',
            'cost'=>'3',
            'power'=>'5000',
        ]);
        CardList::create([
            'id'=>16,
            'color_id'=>1,
            'pack_id'=>'B03',
            'name'=>'ティアラ',
            'cost'=>'3',
            'power'=>'4500',
        ]);
        CardList::create([
            'id'=>17,
            'color_id'=>1,
            'pack_id'=>'B03',
            'name'=>'マラカイトバットー',
            'cost'=>'3',
            'power'=>'5000',
        ]);
    }
}
